Wedding Dress/Controllers/RentController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;
using Wedding_Dress.Models;
namespace Wedding_Dress.Controllers
{
    [SessionState(SessionStateBehavior.Default)]
    public class RentController : Controller
    {
        DBConnection db = new DBConnection();

        // GET: Rent
        public ActionResult Rent(string period)
        {

            db.con.Open();
            List<Rent> files = new List<Rent>();
            SqlCommand cmd = new SqlCommand("select u.u_address,c.user_id,c.dress_id,c.qty from userInfo u inner join Cart c on u.u_id=c.user_id inner join dressinfo d on c.dress_id=d.d_id where u.u_id = (@uid)", db.con);
            cmd.Parameters.AddWithValue("@uid", Session["id"]);
            SqlDataReader sdr = cmd.ExecuteReader();
            while (sdr.Read())
            {
                files.Add(new Rent
                {
                    d_id = int.Parse(sdr["dress_id"].ToString()),
                    r_qty = int.Parse(sdr["qty"].ToString()),
                    u_id = int.Parse(sdr["user_id"].ToString()),
                    r_address = sdr["u_address"].ToString()

                });
            }
            sdr.Close();
            db.con.Close();

            db.con.Open();
            foreach (var item in files)
            {
                SqlCommand cmd1 = new SqlCommand("insert into [rent](d_id,u_id,r_qty,request_date,r_address,r_period) values(@did,@uid,@qty,@date,@address,@period)", db.con);
                cmd1.Parameters.AddWithValue("@did", item.d_id);
                cmd1.Parameters.AddWithValue("@uid", item.u_id);
                cmd1.Parameters.AddWithValue("@qty", item.r_qty);
                cmd1.Parameters.AddWithValue("@address", item.r_address);
                cmd1.Parameters.AddWithValue("@period", period);
                cmd1.Parameters.AddWithValue("@date", DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"));
                cmd1.ExecuteNonQuery();
            }
            db.con.Close();

            db.con.Open();
            string q = "delete from Cart where user_id=(@uid)";
            SqlCommand cmdd = new SqlCommand(q, db.con);
            cmdd.Parameters.AddWithValue("@uid", Session["id"]);

            cmdd.ExecuteNonQuery();
            db.con.Close();
            return View();


        }

        public ActionResult RentRequest()
        {
            Rent rn = new Rent();
            Session["count"] = rn.request_count();

            List<Rent> files = new List<Rent>();

            db.con.Open();
            string q = "SELECT DISTINCT u.u_id,u.u_address,u.u_name,r.request_date FROM userInfo u inner JOIN rent r ON u.u_id = r.u_id inner JOIN dressinfo d ON r.d_id=d.d_id where d.u_id=(@uid)";

            SqlCommand cmd = new SqlCommand(q, db.con);
            cmd.Parameters.AddWithValue("@uid", Session["id"]);
            SqlDataReader sdr = cmd.ExecuteReader();
            while (sdr.Read())
            {
                files.Add(new Rent
                {
                    u_id = int.Parse(sdr["u_id"].ToString()),
                    r_address = sdr["u_address"].ToString(),
                    u_name = sdr["u_name"].ToString(),
                    request_date = Convert.ToDateTime(sdr["request_date"])

                });
            }
            db.con.Close();
            sdr.Close();
            return View(files);
        }

    }

}

Wedding Dress/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.SessionState;
using Wedding_Dress.Models;
namespace Wedding_Dress.Controllers
{
    [SessionState(SessionStateBehavior.Default)]
    public class UserController : Controller
    {
        DBConnection db = new DBConnection();
        
        // GET: User
        
        [HttpGet]
        public ActionResult SignIn()
        {
            return View();
        }
        [HttpPost]
        public ActionResult SignIn(string email, string password)
        {
            db.con.Open();
            string q = "select * from userInfo where u_email='" + email + "' and u_password='" + password + "'";
            SqlCommand cmd = new SqlCommand(q, db.con);
            SqlDataReader sdr = cmd.ExecuteReader();
            sdr.Read();
            if (sdr.HasRows)
            {
                Session["name"] = sdr["u_name"].ToString();
                Session["id"] = sdr["u_id"].ToString();
                Session["address"] = sdr["u_address"].ToString();
                Session["email"] = sdr["u_email"].ToString();
                sdr.Close();
                db.con.Close();
                return RedirectToAction("Women","Home");
            }
            ViewBag.Result = "Invalid Entry Plz Enter Valid Data";
            return View();
        }
        public ActionResult LogOut()
        {
            Session.RemoveAll(); //Clear all session variables
            return RedirectToAction("Women", "Home");                   //...              
        }
        [HttpGet]
        public ActionResult SignUp()
        {
            return View();
        }

        [HttpPost]
     
        public ActionResult SignUp(User u)
        {
            if (ModelState.IsValid)
            {
               db.con.Open();
                string q = "insert into userInfo (u_name,u_email,u_address,u_contact,u_gender,u_password) values(@name,@email,@address,@contact,@gender,@pass)";
                SqlCommand cmd = new SqlCommand(q, db.con);
                cmd.Parameters.AddWithValue("@name", u.Name);
                cmd.Parameters.AddWithValue("@email", u.Email);
                cmd.Parameters.AddWithValue("@address", u.Address);
                cmd.Parameters.AddWithValue("@contact", u.Contact);
                cmd.Parameters.AddWithValue("@pass", u.Password);
                cmd.Parameters.AddWithValue("@gender", u.Gender);
                cmd.ExecuteNonQuery();                           
                db.con.Close();
                return RedirectToAction("SignIn");
            }
            else
            {
                return View("SignUp");

            }
        }

        [HttpGet]
        public ActionResult AllUser()
        {
            List<User> files = new List<User>();

            db.con.Open();
            string q = "select * from userInfo";
            SqlCommand cmd = new SqlCommand(q, db.con);

            SqlDataReader sdr = cmd.ExecuteReader();
            while (sdr.Read())
            {
                files.Add(new User
                {
                    id = int.Parse(sdr["u_id"].ToString()),
                    Name = sdr["u_name"].ToString(),
                    Email = sdr["u_email"].ToString(),
                    Address = sdr["u_address"].ToString(),
                    Contact = sdr["u_contact"].ToString(),
                    Password = sdr["u_password"].ToString(),
                    Gender = sdr["u_gender"].ToString(),
                });
            }
            db.con.Close();
            sdr.Close();
            return View(files);
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            db.con.Open();
            string q = "select * from userInfo where u_id='" + id + "'";
            SqlCommand cmd = new SqlCommand(q, db.con);
            SqlDataReader sdr = cmd.ExecuteReader();
            sdr.Read();
            User u = new User();
            u.id = int.Parse(sdr["u_id"].ToString());
            u.Name = sdr["u_name"].ToString();
            u.Email = sdr["u_email"].ToString();
            u.Address = sdr["u_address"].ToString();
            u.Contact = sdr["u_contact"].ToString();
            u.Password = sdr["u_password"].ToString();
            u.Gender = sdr["u_gender"].ToString();
            sdr.Close();
            db.con.Close();
            return View(u);
        }
        [HttpPost]
        public ActionResult Edit(User u)
        {
            db.con.Open();
            string q = "Update userInfo set u_name =(@name),u_email =(@email),u_contact =(@contact),u_password =(@pass),u_gender =(@gender) where u_id='" + u.id + "'";
            SqlCommand cmd = new SqlCommand(q, db.con);
            cmd.Parameters.AddWithValue("@name", u.Name);
            cmd.Parameters.AddWithValue("@email", u.Email);
            cmd.Parameters.AddWithValue("@address", u.Address);
            cmd.Parameters.AddWithValue("@contact", u.Contact);
            cmd.Parameters.AddWithValue("@pass", u.Password);
            cmd.Parameters.AddWithValue("@gender", u.Gender);
            cmd.ExecuteNonQuery();
            db.con.Close();
            return RedirectToAction("AllUser");
        }

        public ActionResult Delete(int id)
        {
            db.con.Open();
            string q = "delete from userInfo where u_id='" + id + "'";
            SqlCommand cmd = new SqlCommand(q, db.con);
            cmd.ExecuteNonQuery();
            db.con.Close();
            return RedirectToAction("AllUser");
        }
    }
}

Wedding Dress/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Women</title>
    <link href="~/css/animate.css" rel="stylesheet" />
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/css/main.css" rel="stylesheet" />
    <link href="~/assets/css/jquery.simpleLens.css" rel="stylesheet" />
    <link href="~/css/prettyPhoto.css" rel="stylesheet" />
    <link href="~/assets/css/bootstrap.css" rel="stylesheet" />
    <link href="~/assets/css/sequence-theme.modern-slide-in.css" rel="stylesheet" />
    <link href="~/css/price-range.css" rel="stylesheet" />

    <link href="~/assets/css/slick.css" rel="stylesheet" />
    <link href="~/assets/css/font-awesome.css" rel="stylesheet" />
    <link href="~/css/responsive.css" rel="stylesheet" />
    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="~/assets/css/nouislider.css" rel="stylesheet" />
    <link href="css/font-awesome.min.css" rel="stylesheet">
    <link href="css/prettyPhoto.css" rel="stylesheet">
    <link href="css/price-range.css" rel="stylesheet">
    <link href="~/assets/css/style.css" rel="stylesheet" />
    <link href="css/animate.css" rel="stylesheet">
    <link href="css/main.css" rel="stylesheet">
    <link href="css/responsive.css" rel="stylesheet">
    <link href="css/font-awesome.css" rel="stylesheet">
    <!-- Bootstrap -->
    <link href="~/assets/css/bootstrap.css" rel="stylesheet">
    <!-- SmartMenus jQuery Bootstrap Addon CSS -->
    <link href="~/assets/css/jquery.smartmenus.bootstrap.css" rel="stylesheet">
    <!-- Product view slider -->
    <link rel="stylesheet" type="text/css" href="~/assets/css/jquery.simpleLens.css">
    <!-- slick slider -->
    <link rel="stylesheet" type="text/css" href="~/assets/css/slick.css">
    <!-- price picker slider -->
    <link rel="stylesheet" type="text/css" href="~/assets/css/nouislider.css">
    <!-- Theme color -->
    <link id="switcher" href="~/assets/css/theme-color/default-theme.css" rel="stylesheet">
    <!-- <link id="switcher" href="css/theme-color/bridge-theme.css" rel="stylesheet"> -->
    <!-- Top Slider CSS -->
    <link href="~/assets/css/sequence-theme.modern-slide-in.css" rel="stylesheet" media="all">

    <!-- Main style sheet -->
    <link href="~/assets/css/style.css" rel="stylesheet">
    <!--[if lt IE 9]>
    <script src="js/html5shiv.js"></script>
    <script src="js/respond.min.js"></script>
    <![endif]-->
    <link rel="shortcut icon" href="images/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="images/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="images/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="images/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="images/ico/apple-touch-icon-57-precomposed.png">
</head><!--/head-->

<body>

    <header id="aa-header">
        <!-- start header top  -->
        <div class="aa-header-top">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="aa-header-top-area">
                            <!-- start header top left -->
                            <div class="aa-header-top-left">

                            </div>

                            <!-- / header top left -->
                            <div class="aa-header-top-right">
                                <ul class="aa-head-top-nav-right">
                                    @if (Session["email"] != null)
                                    {
                                        <li><a href="" data-toggle="modal" data-target="#login-modal" style="font-size:15px;font-weight:bold;color:black">@Session["name"]</a></li>
                                        <li><a href='@Url.Action("LogOut","User")' data-toggle="modal" class="btn btn-danger" style="font-size:15px;font-weight:bold;color:white">LogOut</a></li>
                                    }
                                    else
                                    {
                                        <li><a href='@Url.Action("SignIn","User")' data-toggle="modal" class="btn btn-danger" style="font-size:15px;font-weight:bold;color:white">Sign In</a></li>
                                        <li><a href='@Url.Action("SignUp","User")' data-toggle="modal" class="btn btn-danger" style="font-size:15px;font-weight:bold;color:white">Sign Up</a></li>
                                    }
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- / header top  -->
        <!-- start header bottom  -->
        <div class="aa-header-bottom">
            <div class="container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="aa-header-bottom-area">
                            <!-- logo  -->
                            <div class="aa-logo">
                                <!-- Text based logo -->
                                <a href="index.html">
                                    <p>Wedding <strong>Dress</strong> <span></span></p>
                                </a>

                                <!-- img based logo -->
                                <!-- <a href="index.html"><img src="img/logo.jpg" alt="logo img"></a> -->
                            </div>
                            <!-- / logo  -->
                            <!-- cart box -->
                            @if (Session["email"] != null)
                            {
                                <div class="aa-cartbox">
                                    <a class="aa-cart-link" href='@Url.Action("Cart","Cart")'>
                                        <span class="fa fa-shopping-basket"></span>
                                        <span class="aa-cart-title">CART</span>
                                        <span class="aa-cart-notify"> @Session["Cart_Count"]</span>
                                    </a>
                                </div>
                            }
                            <!-- / cart box -->
                            <!-- search box -->
                            <div class="aa-search-box">
                                <form action='@Url.Action("Search","Home")' method="post">
                                    <input type="text" name="search" id="" placeholder="Search here Dresses ">
                                    <button type="submit"><span class="fa fa-search"></span></button>
                                </form>
                            </div>
                            <!-- / search box -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- / header bottom  -->
    </header>
    <!-- / header section -->
    <!-- menu -->
    <section id="menu">
        <div class="container">
            <div class="menu-area">
                <!-- Navbar -->
                <div class="navbar navbar-default" role="navigation">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="sr-only">Toggle navigation</span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="navbar-collapse collapse">
                        <!-- Left nav -->
                        <ul class="nav navbar-nav">
                            <li><a href='@Url.Action("Women","Home")'>Women</a></li>
                            <li><a href='@Url.Action("Men","Home")'>Men</a></li>
                            @if (Session["email"] != null)
                            {
                                <li><a href='@Url.Action("Dress","Dress")'>My Dress</a></li>
                                <li><a href='@Url.Action("RentRequest","Rent")'>Request(@Session["count"])</a></li>
                            }
                        </ul>
                    </div><!--/.nav-collapse -->
                </div>
            </div>
        </div>
    </section>

    @*<section id="slider">
        <!--slider-->
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div id="slider-carousel" class="carousel slide" data-ride="carousel">


                        <div class="carousel-inner">
                            <div class="item active">
                                <div class="col-sm-6">
                                    <h1><span>Wedding</span>-Dress</h1>
                                </div>
                                <div class="col-sm-6">
                                    <img src="~/images/home/girl1.jpg" class="girl img-responsive" alt="" />
                                </div>
                            </div>

                        </div>


                    </div>

                </div>
            </div>
        </div>
    </section><!--/slider-->*@

    <section>
        <div class="container">
            <div class="row">
                <div class="col-sm-12 padding-right">
                    @RenderBody()

                </div>
            </div>
        </div>
    </section>

    <script src="js/bootstrap.js"></script>
    <!-- SmartMenus jQuery plugin -->
    <script type="text/javascript" src="~/assets/js/jquery.smartmenus.js"></script>
    <!-- SmartMenus jQuery Bootstrap Addon -->
    <script type="text/javascript" src="~/assets/js/jquery.smartmenus.bootstrap.js"></script>
    <!-- To Slider JS -->
    <script src="~/assets/js/sequence.js"></script>
    <script src="js/sequence-theme.modern-slide-in.js"></script>
    <!-- Product view slider -->
    <script type="text/javascript" src="~/assets/js/jquery.simpleGallery.js"></script>
    <script type="text/javascript" src="~/assets/js/jquery.simpleLens.js"></script>
    <!-- slick slider -->
    <script type="text/javascript" src="~/assets/js/slick.js"></script>
    <!-- Price picker slider -->
    <script type="text/javascript" src="~/assets/js/nouislider.js"></script>
    <!-- Custom js -->
    <script src="~/assets/js/custom.js"></script>


    <script src="~/js/bootstrap.min.js"></script>
    <script src="~/js/contact.js"></script>
    <script src="~/js/gmaps.js"></script>
    <script src="~/js/html5shiv.js"></script>
    <script src="~/js/jquery.js"></script>
    <script src="~/js/jquery.prettyPhoto.js"></script>
    <script src="~/js/jquery.scrollUp.min.js"></script>
    <script src="~/js/main.js"></script>
    <script src="~/js/price-range.js"></script>

    <script src="js/jquery.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/jquery.scrollUp.min.js"></script>
    <script src="js/price-range.js"></script>
    <script src="js/jquery.prettyPhoto.js"></script>
    <script src="js/main.js"></script>
</body>
</html>